import React, { useState, useEffect } from 'react';
import { modules, contentVersion } from './content';
import { createSession, answerSession, advanceSession, loadProgress } from './lib/quiz';
import './styles.css';
export default function Classic() {
  const [sessions,setSessions]=useState(()=>loadProgress(localStorage,modules,contentVersion));
  const [active,setActive]=useState(null);
  const [input,setInput]=useState('');
  const [storageError,setStorageError]=useState(false);
  const [reset,setReset]=useState(false);
  useEffect(()=>{try {localStorage.setItem('learnloop-progress',JSON.stringify({version:contentVersion,sessions}));setStorageError(false);}catch{setStorageError(true);}},[sessions]);
  const module=modules.find(m=>m.id===active);
  const session=module && (sessions[active] || createSession(module.questions));
  const question=module?.questions.find(q=>q.id===session.queue[0]);
  const mastered=Object.values(sessions).reduce((n,s)=>n+s.mastered.length,0);
  const total=modules.reduce((n,m)=>n+m.questions.length,0);
  function open(id){setActive(id);setInput('');setReset(false);}
  function update(s){setSessions(prev=>({...prev,[active]:s}));}
  function submit(e){e.preventDefault();if(input.trim())update(answerSession(session,question,input));}
  function next(){update(advanceSession(session));setInput('');}
  return <div className="shell"><header><button className="brand" onClick={()=>open(null)} aria-label="LearnLoop, início"><span className="logo">↻</span>LearnLoop</button><span className="header-label">INGLÊS • PRATIQUE E APRENDA</span><span className="points">✦ {Object.values(sessions).reduce((n,s)=>n+s.score,0)} pontos</span></header>
  {storageError && <p role="alert" className="notice">Não foi possível salvar neste navegador. Seu progresso continua disponível enquanto esta página estiver aberta.</p>}
  {!module ? <main><section className="hero"><div><p className="eyebrow">UM ACERTO DE CADA VEZ</p><h1>Aprender é dar<br/>mais uma volta<span>.</span></h1><p className="intro">Pratique inglês no seu ritmo. Errou? Aprenda com a explicação e tente de novo até acertar todas.</p><button className="primary" onClick={()=>open(modules.find(m=>(sessions[m.id]?.mastered.length||0)<m.questions.length)?.id || modules[0].id)}>Continuar aprendendo <span>→</span></button></div><aside className="journey"><span className="orbit">↻</span><h2>Seu caminho de aprendizagem</h2><p><strong>{mastered}</strong> de {total} questões dominadas</p><progress value={mastered} max={total}/><small>O progresso fica salvo neste navegador.</small></aside></section><div className="section-title"><h2>Escolha sua próxima volta</h2><span>5 módulos · {total} questões</span></div><section className="grid">{modules.map((m,i)=>{const s=sessions[m.id];const count=s?.mastered.length||0;return <button key={m.id} className="module-card" onClick={()=>open(m.id)}><span className="module-top"><span className="badge">0{i+1}</span><span>{count===m.questions.length?'✓ Concluído':count?'Em andamento':'Vamos começar'}</span></span><h3>{m.title}</h3><p>{m.subtitle}</p><progress value={count} max={m.questions.length}/><div className="card-bottom"><span>{count}/{m.questions.length} dominadas</span><b>→</b></div></button>})}</section></main> : <main className="quiz"><button className="back" onClick={()=>open(null)}>← Todos os módulos</button><div className="section-title"><div><p className="eyebrow">PRÁTICA GUIADA</p><h1>{module.title}</h1></div><button className="quiet" onClick={()=>setReset(!reset)}>Reiniciar módulo</button></div>{reset && <div className="notice">Apagar o progresso deste módulo? <button onClick={()=>{update(createSession(module.questions));setInput('');setReset(false);}}>Sim, reiniciar</button> <button onClick={()=>setReset(false)}>Cancelar</button></div>}
  <div className="stats"><span>{session.mastered.length}/{module.questions.length} dominadas</span><span>{session.score} pontos</span><span>{session.attempts} tentativas</span></div><progress value={session.mastered.length} max={module.questions.length}/>
  <details className="lesson"><summary>Consultar resumo {module.reading?'e texto de leitura':''}</summary><p>{module.lesson}</p>{module.reading && <p className="reading" lang="en">{module.reading}</p>}</details>
  {question ? <section className="question" key={question.id}><div className="question-meta"><span>{question.origin==='pdf'?'Da apresentação':'Prática extra'}</span><span>{session.queue.length} na fila</span></div><h2 lang="en">{question.prompt}</h2><p className="hint">{question.options?'Escolha a resposta correta.':'Escreva a resposta em inglês. Pontuação e maiúsculas não alteram a correção.'}</p><form onSubmit={submit}>{question.options ? <div className="options">{question.options.map(option=><button type="button" key={option} disabled={!!session.feedback} aria-pressed={input===option} className={input===option?'selected':''} onClick={()=>setInput(option)}>{option}</button>)}</div> : <input key={question.id} autoFocus aria-label="Sua resposta" placeholder="Sua resposta…" autoComplete="off" spellCheck="false" value={session.feedback?.answer ?? input} disabled={!!session.feedback} onChange={e=>setInput(e.target.value)}/>}{!session.feedback && <button className="primary" disabled={!input.trim()} type="submit">Verificar resposta →</button>}</form>{session.feedback && <div role="status" className={'feedback '+(session.feedback.correct?'correct':'incorrect')}><h3>{session.feedback.correct?'✓ Muito bem! +10 pontos':'↻ Vamos aprender com esta tentativa'}</h3>{!session.feedback.correct && <p>Resposta: <strong lang="en">{question.answers[0]}</strong></p>}<p>{question.explanation}</p>{!session.feedback.correct && <small>Esta questão voltará ao fim da fila para você praticar novamente.</small>}<button autoFocus className="primary" onClick={next}>Continuar →</button></div>}</section> : <section className="completion"><span>✦</span><h2>Mais uma volta completa!</h2><p>Você acertou todas as {module.questions.length} questões deste módulo.</p><p>{session.score} pontos · {session.attempts} tentativas · {session.mistakes} erros revisados</p><button className="primary" onClick={()=>open(null)}>Escolher próximo módulo →</button></section>}
  </main>}<footer>LearnLoop · Praticar. Entender. Tentar de novo.<span>Conteúdo baseado na apresentação de Eli Hungria.</span></footer></div>
}
