import React, { useEffect, useState } from 'react';
import content from './content/adventure.json';
import { optionsFor } from './lib/adventure';
import { forms, formsProgress, startForm, answerForm, formHint } from './lib/forms';
const bank=content.questions;
export default function Forms({state,setState,onBack}){
 const [input,setInput]=useState('');const [now,setNow]=useState(Date.now());
 const f=formsProgress(state);const c=f.challenge;
 useEffect(()=>{if(c?.status!=='running')return;const tick=setInterval(()=>setNow(Date.now()),100);return ()=>clearInterval(tick);},[c?.status,c?.deadline]);
 useEffect(()=>{window.scrollTo(0,0);},[c?.status,c?.form]);
 const seconds=c?Math.max(0,Math.ceil((c.deadline-now)/1000)):30;
 const item=c?.queue[0];const q=bank.find(q=>q.id===item?.id);
 const last=c?.log.at(-1);
 function start(){setInput('');setNow(Date.now());setState(s=>startForm(s,bank));}
 function answer(value){if(value.trim()){setState(s=>answerForm(s,bank,value));setInput('');}}
 return <main className="forms-view"><button className="text-button" onClick={onBack}>← Voltar ao mapa</button><section className="forms-heading"><p className="kicker">TREINAMENTO DA RESPIRAÇÃO DO SOL</p><h1>Conquiste suas <em>13 formas.</em></h1><p>Uma trilha independente do mapa. Cinco acertos em 30 segundos: as questões ficam mais difíceis, o tempo permanece.</p><div className="forms-count">✦ {f.completed}/13 formas conquistadas</div></section>
 {c?.status==='running'&&q?<section className="timed-arena"><div className="timed-header"><div><p className="kicker">{c.form+1}ª FORMA</p><h2>{forms[c.form].name}</h2></div><div className={'countdown '+(seconds<=10?'urgent':'')} role="timer" aria-label={`${seconds} segundos restantes`}><strong>{seconds}</strong><small>segundos</small></div></div><progress value={seconds} max={30} aria-label="Tempo restante"/><div className="battle-meta"><span>{c.solved.length}/5 acertos</span><span>{c.earnedXp} XP neste desafio</span><span>Sem pausa</span></div>{last&&<p role="status" className={'timed-flash '+(last.correct?'hit':'miss')}>{last.correct?`✓ Acertou! +${last.earnedXp} XP`:'↻ Errou. A questão voltará em outro formato.'}</p>}<div className="question-tags"><span>Nível {q.level}</span><span>{item.mode==='choice'?'Marcar':'Escrever'}</span><span>{item.language==='pt'?'Português':'English'}</span></div><div key={q.id+'-'+item.retries}><h2 className="timed-prompt" lang={item.language==='pt'?'pt-BR':'en'}>{item.language==='pt'?q.promptPt:q.promptEn}</h2><details className="translation"><summary>Ver tradução do enunciado</summary><p>{item.language==='pt'?q.promptEn:q.promptPt}</p></details>{q.topic==='climate-of-brazil'&&<details className="reading-panel"><summary>Consultar texto de leitura</summary><p lang="en">{content.reading}</p></details>}{item.mode==='choice'?<div className="battle-options">{optionsFor(q).map((option,i)=><button key={option} onClick={()=>answer(option)} disabled={seconds===0}><span>{String.fromCharCode(65+i)}</span>{option}</button>)}</div>:<form onSubmit={e=>{e.preventDefault();answer(input);}}><label className="answer-label" htmlFor="timed-answer">Sua resposta</label><input id="timed-answer" autoFocus value={input} onChange={e=>setInput(e.target.value)} disabled={seconds===0} autoComplete="off" spellCheck="false" placeholder="Escreva e pressione Enter…"/><button className="adventure-primary" disabled={!input.trim()||seconds===0}>Responder →</button><div className="translation">{c.hintedIds.includes(q.id)?<><p>{q.explanation}</p><small>Dica utilizada: este acerto vale 5 XP.</small></>:<button type="button" className="text-button" disabled={seconds===0} onClick={()=>setState(s=>formHint(s))}>Ver dica · o acerto valerá 5 XP (metade)</button>}</div></form>}</div><p className="timed-note">As alternativas enviam a resposta com um toque. Na escrita, use Enter. O relógio continua se você sair ou recarregar.</p></section>:
 <>{c&&<section className={'form-result '+(c.status==='won'?'won':'lost')} role="status"><span className="form-seal">{c.status==='won'?'✦':'↻'}</span><p className="kicker">{c.status==='won'?'NOVA TÉCNICA CONQUISTADA':'O TEMPO TERMINOU'}</p><h2>{c.status==='won'?forms[c.form].name:'Sua técnica precisa de mais uma volta.'}</h2><p>{c.solved.length}/5 acertos · {c.earnedXp} XP conquistados</p><p>{c.status==='won'?f.completed===13?'Você conquistou as 13 formas! Continue sua aventura no mapa.':'A próxima forma está disponível.':'Revise as explicações abaixo e tente a mesma forma com um novo sorteio.'}</p></section>}{f.completed<13&&<section className="form-start"><h2>{f.completed+1}ª Forma · {forms[f.completed].name}</h2><p>Níveis {Math.min(...forms[f.completed].levels)}{Math.min(...forms[f.completed].levels)!==Math.max(...forms[f.completed].levels)?'–'+Math.max(...forms[f.completed].levels):''} · cinco questões · 30 segundos no total.</p><p>Erros retornam à fila. Para conquistar a forma, acerte as cinco antes que o tempo acabe. Tradução e leitura ficam disponíveis; o relógio não para.</p><button className="adventure-primary" onClick={start}>{c?.status==='lost'?'Tentar novamente':'Começar desafio de 30 segundos'} →</button></section>}{c&&<section className="form-review"><h2>Revisão do desafio</h2><p>Leia a explicação de cada tentativa antes do próximo treino.</p>{c.log.length===0?<p>Você não enviou respostas nesta tentativa.</p>:c.log.map((l,i)=>{const question=bank.find(q=>q.id===l.id);return <details key={i} className="review-item"><summary>{l.correct?'✓':'↻'} Tentativa {i+1} · {l.correct?'Acerto':'Erro'} · {l.earnedXp} XP</summary><p>{question.promptPt}</p><p>Sua resposta: <strong>{l.answer}</strong></p><p>Resposta correta: <strong>{question.answers[0]}</strong></p><p>{question.explanation}</p></details>})}{c.queue.length>0&&<details className="review-item"><summary>Questões que ficaram pendentes</summary>{c.queue.map(i=>{const pending=bank.find(q=>q.id===i.id);return <div key={i.id}><p>{pending.promptPt}</p><p><strong>{pending.answers[0]}</strong> · {pending.explanation}</p></div>})}</details>}</section>}</>}
 <section className="forms-collection" aria-label="Suas 13 formas">{forms.map(form=><div key={form.id} className={'form-tile '+(form.id<f.completed?'earned':form.id===f.completed?'available':'locked')}><span>{form.id<f.completed?'✦':String(form.id+1).padStart(2,'0')}</span><h3>{form.name}</h3><small>{form.id<f.completed?'Conquistada':form.id===f.completed?'Próxima conquista':'Conquiste a forma anterior'}</small></div>)}</section></main>;
}
