import React, { useEffect, useState } from 'react';
import content from './content/adventure.json';
import { optionsFor } from './lib/adventure';
const bank=content.questions;
export function TimedChallenge({challenge:c,title,subtitle,duration=30000,onAnswer,onHint}){
 const [input,setInput]=useState('');const [now,setNow]=useState(Date.now());
 useEffect(()=>{const tick=setInterval(()=>setNow(Date.now()),100);return ()=>clearInterval(tick);},[]);
 const seconds=Math.max(0,Math.ceil((c.deadline-now)/1000));
 const item=c.queue[0];const q=bank.find(q=>q.id===item.id);const last=c.log.at(-1);
 function answer(value){if(value.trim()){onAnswer(value);setInput('');}}
 return <section className="timed-arena"><div className="timed-header"><div><p className="kicker">{subtitle}</p><h2>{title}</h2></div><div className={'countdown '+(seconds<=10?'urgent':'')} role="timer" aria-label={`${seconds} segundos restantes`}><strong>{seconds}</strong><small>segundos</small></div></div><progress value={seconds} max={duration/1000} aria-label="Tempo restante"/><div className="battle-meta"><span>{c.solved.length}/5 acertos</span><span>{c.earnedXp} XP neste desafio</span><span>Sem pausa</span></div>{last&&<p role="status" className={'timed-flash '+(last.correct?'hit':'miss')}>{last.correct?`✓ Acertou! +${last.earnedXp} XP`:'↻ Errou. A questão voltará em outro formato.'}</p>}<div className="question-tags"><span>Nível {q.level}</span><span>{item.mode==='choice'?'Marcar':'Escrever'}</span><span>{item.language==='pt'?'Português':'English'}</span></div><div key={q.id+'-'+item.retries}><h2 className="timed-prompt" lang={item.language==='pt'?'pt-BR':'en'}>{item.language==='pt'?q.promptPt:q.promptEn}</h2><details className="translation"><summary>Ver tradução do enunciado</summary><p>{item.language==='pt'?q.promptEn:q.promptPt}</p></details>{q.topic==='climate-of-brazil'&&<details className="reading-panel"><summary>Consultar texto de leitura</summary><p lang="en">{content.reading}</p></details>}{item.mode==='choice'?<div className="battle-options">{optionsFor(q).map((option,i)=><button key={option} onClick={()=>answer(option)} disabled={seconds===0}><span>{String.fromCharCode(65+i)}</span>{option}</button>)}</div>:<form onSubmit={e=>{e.preventDefault();answer(input);}}><label className="answer-label" htmlFor="timed-answer">Sua resposta</label><input id="timed-answer" autoFocus value={input} onChange={e=>setInput(e.target.value)} disabled={seconds===0} autoComplete="off" spellCheck="false" placeholder="Escreva e pressione Enter…"/><button className="adventure-primary" disabled={!input.trim()||seconds===0}>Responder →</button><div className="translation">{c.hintedIds.includes(q.id)?<><p>{q.explanation}</p><small>Dica utilizada: este acerto vale 5 XP.</small></>:<button type="button" className="text-button" disabled={seconds===0} onClick={onHint}>Ver dica · o acerto valerá 5 XP (metade)</button>}</div></form>}</div><p className="timed-note">As alternativas enviam a resposta com um toque. Na escrita, use Enter. O relógio continua se você sair ou recarregar.</p></section>;
}
export function ChallengeReview({challenge:c}){return <section className="form-review"><h2>Revisão do desafio</h2><p>Leia a explicação de cada tentativa antes do próximo treino.</p>{c.log.length===0?<p>Você não enviou respostas nesta tentativa.</p>:c.log.map((l,i)=>{const question=bank.find(q=>q.id===l.id);return <details key={i} className="review-item"><summary>{l.correct?'✓':'↻'} Tentativa {i+1} · {l.correct?'Acerto':'Erro'} · {l.earnedXp} XP</summary><p>{question.promptPt}</p><p>Sua resposta: <strong>{l.answer}</strong></p><p>Resposta correta: <strong>{question.answers[0]}</strong></p><p>{question.explanation}</p></details>})}{c.queue.length>0&&<details className="review-item"><summary>Questões que ficaram pendentes</summary>{c.queue.map(i=>{const pending=bank.find(q=>q.id===i.id);return <div key={i.id}><p>{pending.promptPt}</p><p><strong>{pending.answers[0]}</strong> · {pending.explanation}</p></div>})}</details>}</section>;}
